name: Build EmulationStation Logs to S3 Container Image (multi-arch)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./emulation-station-log-parser
          file: ./emulation-station-log-parser/Containerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: evanshortiss/emulation-station-logs-to-s3:latest, evanshortiss/emulation-station-logs-to-s3:${{ github.sha }}